// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5F68Fl2VOBAoZG52OcpmjswWn_83_7Vg',
    appId: '1:372638686987:web:a46ace0072af3ac03fcc0e',
    messagingSenderId: '372638686987',
    projectId: 'cody-authenticator',
    authDomain: 'cody-authenticator.firebaseapp.com',
    storageBucket: 'cody-authenticator.firebasestorage.app',
    measurementId: 'G-F6LR535431',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGs06PtToanHLKCq8As-ffvydoz0S5I2M',
    appId: '1:372638686987:android:c7051d4046525f3f3fcc0e',
    messagingSenderId: '372638686987',
    projectId: 'cody-authenticator',
    storageBucket: 'cody-authenticator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADj92L2x5dZ74j_1G_YYeiqbdRrXQGxV4',
    appId: '1:372638686987:ios:1622b469ae8668f43fcc0e',
    messagingSenderId: '372638686987',
    projectId: 'cody-authenticator',
    storageBucket: 'cody-authenticator.firebasestorage.app',
    iosBundleId: 'dev.tutorialwork.Cody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADj92L2x5dZ74j_1G_YYeiqbdRrXQGxV4',
    appId: '1:372638686987:ios:d0dddf38495a9ee33fcc0e',
    messagingSenderId: '372638686987',
    projectId: 'cody-authenticator',
    storageBucket: 'cody-authenticator.firebasestorage.app',
    iosBundleId: 'com.example.cody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5F68Fl2VOBAoZG52OcpmjswWn_83_7Vg',
    appId: '1:372638686987:web:f0fb34df4ee5acea3fcc0e',
    messagingSenderId: '372638686987',
    projectId: 'cody-authenticator',
    authDomain: 'cody-authenticator.firebaseapp.com',
    storageBucket: 'cody-authenticator.firebasestorage.app',
    measurementId: 'G-MEDS1H72J7',
  );

}